# Generated by Django 2.2.8 on 2020-03-11 15:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('finish', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultDeepstream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('car_number', models.CharField(max_length=16)),
                ('car_brand', models.CharField(max_length=32)),
                ('car_color', models.CharField(max_length=32)),
                ('probability', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('car_photo', models.ImageField(upload_to='images/')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_s_app.Camera')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_s_app.Request')),
            ],
        ),
        migrations.CreateModel(
            name='RequestCameraURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_s_app.Camera')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_s_app.Request')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='cameras',
            field=models.ManyToManyField(through='c_s_app.RequestCameraURL', to='c_s_app.Camera'),
        ),
    ]
