# Generated by Django 2.2.8 on 2020-03-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_s_app', '0002_resultdeepstream_car_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='azimuth',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='lat',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='long',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
