# Generated by Django 2.2.8 on 2020-03-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_s_app', '0006_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultdeepstream',
            name='car_brand',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='resultdeepstream',
            name='car_color',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='resultdeepstream',
            name='car_generation',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='resultdeepstream',
            name='car_model',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='resultdeepstream',
            name='car_number',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='resultdeepstream',
            name='car_photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
