# Generated by Django 2.2.8 on 2020-03-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_s_app', '0010_mark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Generation',
            new_name='GenerationList',
        ),
    ]
