# Generated by Django 2.2.8 on 2020-03-27 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c_s_app', '0011_auto_20200327_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('mark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='c_s_app.Mark')),
            ],
        ),
    ]
