# Generated by Django 2.2.8 on 2020-03-27 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c_s_app', '0011_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='model',
            name='generation',
        ),
        migrations.AddField(
            model_name='generation',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='c_s_app.Model'),
        ),
        migrations.AlterField(
            model_name='generation',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='c_s_app.GenerationList'),
        ),
    ]
