# Generated by Django 2.2.8 on 2020-03-27 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c_s_app', '0012_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='c_s_app.Model')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='c_s_app.GenerationList')),
            ],
        ),
    ]
