# Generated by Django 2.2.8 on 2020-03-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_s_app', '0012_auto_20200327_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Generation',
        ),
    ]
