# Generated by Django 2.2.8 on 2020-03-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_s_app', '0013_generation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generation',
            old_name='name',
            new_name='generation',
        ),
    ]
