# Generated by Django 2.2.8 on 2020-03-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_s_app', '0014_auto_20200327_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generation',
            old_name='generation',
            new_name='name',
        ),
    ]
