# Generated by Django 2.2.8 on 2020-03-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_s_app', '0015_auto_20200327_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultdeepstream',
            name='car_brand',
        ),
        migrations.RemoveField(
            model_name='resultdeepstream',
            name='car_color',
        ),
        migrations.RemoveField(
            model_name='resultdeepstream',
            name='car_generation',
        ),
        migrations.RemoveField(
            model_name='resultdeepstream',
            name='car_model',
        ),
    ]
