# Generated by Django 2.2.8 on 2020-03-29 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c_s_app', '0016_auto_20200329_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultdeepstream',
            name='car_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='c_s_app.Color'),
        ),
        migrations.AddField(
            model_name='resultdeepstream',
            name='car_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='c_s_app.Generation'),
        ),
        migrations.AlterField(
            model_name='resultdeepstream',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='c_s_app.Camera'),
        ),
        migrations.AlterField(
            model_name='resultdeepstream',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='c_s_app.Request'),
        ),
        migrations.AlterField(
            model_name='resultdeepstream',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
