# Generated by Django 2.2.8 on 2020-04-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_s_app', '0017_auto_20200329_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationlist',
            name='name',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
