# Generated by Django 2.2.8 on 2020-04-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_s_app', '0018_auto_20200406_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
