# Generated by Django 2.2.8 on 2020-04-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_s_app', '0020_generation_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generation',
            name='path',
        ),
    ]
