# Generated by Django 2.2.8 on 2020-04-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_s_app', '0021_remove_generation_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='path',
            field=models.FilePathField(null=True, path=None),
        ),
    ]
