# Generated by Django 2.2.8 on 2020-04-13 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_s_app', '0023_auto_20200413_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcameraurl',
            name='recognition_progress',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='resultdeepstream',
            name='color_probability',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
