# Generated by Django 2.2.8 on 2020-03-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_s_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultdeepstream',
            name='car_video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
