# Generated by Django 2.2.8 on 2020-03-27 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_s_app', '0007_auto_20200327_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultdeepstream',
            name='car_probability',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='resultdeepstream',
            name='color_probability',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
