# Generated by Django 2.2.8 on 2020-03-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_s_app', '0013_delete_generation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenerationList',
        ),
    ]
