# Generated by Django 2.2.8 on 2020-03-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_s_app', '0016_generationcar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generationcar',
            name='model',
        ),
        migrations.RemoveField(
            model_name='generationcar',
            name='name',
        ),
        migrations.RemoveField(
            model_name='model',
            name='mark',
        ),
        migrations.DeleteModel(
            name='Generation',
        ),
        migrations.DeleteModel(
            name='GenerationCar',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
